import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import {fileURLToPath} from 'node:url';

const DEFAULT_INPUT = 'output/production_plan.json';
const DEFAULT_OUTPUT = 'output/subtitles.ass';

const STYLE_BY_ASPECT_RATIO = {
  '16:9': {
    playResX: 1920,
    playResY: 1080,
    fontSize: 68,
    marginL: 160,
    marginR: 160,
    marginV: 100,
    chorusFontSize: 76,
    chorusMarginV: 125
  },
  '9:16': {
    playResX: 1080,
    playResY: 1920,
    fontSize: 72,
    marginL: 90,
    marginR: 90,
    marginV: 140,
    chorusFontSize: 82,
    chorusMarginV: 170
  },
  '1:1': {
    playResX: 1080,
    playResY: 1080,
    fontSize: 66,
    marginL: 110,
    marginR: 110,
    marginV: 100,
    chorusFontSize: 74,
    chorusMarginV: 125
  }
};

// emotional_tone values that map to the Chorus style (larger, warm color, higher position)
const CHORUS_TONES = new Set(['uplifting', 'energetic', 'epic', 'triumphant', 'joyful', 'powerful']);

async function main() {
  try {
    const args = parseArgs(process.argv.slice(2));
    const inputPath = path.resolve(process.cwd(), args.input ?? DEFAULT_INPUT);
    const outputPath = path.resolve(process.cwd(), args.output ?? DEFAULT_OUTPUT);

    const plan = await readProductionPlan(inputPath);
    validatePlanForSubtitles(plan);

    const ass = generateAssSubtitles(plan);

    await fs.mkdir(path.dirname(outputPath), {recursive: true});
    await fs.writeFile(outputPath, ass, 'utf8');

    console.log(`ASS subtitles written to ${outputPath}`);
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}

export function generateAssSubtitles(plan) {
  const aspectRatio = plan.project?.aspect_ratio ?? '16:9';
  const style = STYLE_BY_ASPECT_RATIO[aspectRatio] ?? STYLE_BY_ASPECT_RATIO['16:9'];
  const assStyle = plan.subtitles?.ass_style ?? {};
  const karaokeHighlight = plan.subtitles?.karaoke_highlight === true;
  const font = sanitizeStyleValue(assStyle.font || plan.project?.font_style || 'Arial');
  const fontSize = clampNumber(Number(assStyle.font_size || style.fontSize), style.fontSize, 28, 140);
  const primaryColor = sanitizeColor(assStyle.primary_color, '&H00FFFFFF');
  const highlightColor = sanitizeColor(assStyle.highlight_color, '&H0050C8FF');
  const outlineColor = sanitizeColor(assStyle.outline_color, '&H00151515');

  const lines = [
    '[Script Info]',
    '; Generated by lyric-video-generation-pipeline Phase 2',
    'ScriptType: v4.00+',
    'WrapStyle: 0',
    'ScaledBorderAndShadow: yes',
    `PlayResX: ${style.playResX}`,
    `PlayResY: ${style.playResY}`,
    '',
    '[V4+ Styles]',
    'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    // Default style — white, bottom center, thick outline + deep shadow
    buildStyleLine(
      'Default', font, fontSize,
      primaryColor, highlightColor, outlineColor, '&H70000000',
      '-1', '0', '0', '0', '100', '100', '1', '0',
      '1', '4', '2', '2',
      style.marginL, style.marginR, style.marginV
    ),
    // Chorus style — warm gold, bottom center but higher, slightly larger font
    buildStyleLine(
      'Chorus', font, clampNumber(style.chorusFontSize, style.chorusFontSize, 28, 160),
      '&H0050C8FF', highlightColor, '&H00000000', '&H70000000',
      '-1', '0', '0', '0', '100', '100', '2', '0',
      '1', '5', '3', '2',
      style.marginL, style.marginR, style.chorusMarginV
    ),
    '',
    '[Events]',
    'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text'
  ];

  for (const segment of plan.segments) {
    const start = toAssTimestamp(segment.start);
    const end = toAssTimestamp(segment.end);
    const duration = Number(segment.duration ?? 0);
    const fadeIn = duration < 1.5 ? 120 : 280;
    const fadeOut = duration < 1.5 ? 180 : 380;
    const fadeTag = `{\\fad(${fadeIn},${fadeOut})}`;

    const tone = String(segment.style?.emotional_tone ?? '').toLowerCase().trim();
    const styleName = CHORUS_TONES.has(tone) ? 'Chorus' : 'Default';

    const text = karaokeHighlight
      ? fadeTag + buildKaraokeText(segment.lyric, segment.duration)
      : fadeTag + escapeAssText(segment.lyric);

    lines.push(`Dialogue: 0,${start},${end},${styleName},,0,0,0,,${text}`);
  }

  return `${lines.join('\n')}\n`;
}

function buildStyleLine(
  name, fontname, fontsize,
  primaryColor, secondaryColor, outlineColor, backColor,
  bold, italic, underline, strikeOut, scaleX, scaleY, spacing, angle,
  borderStyle, outline, shadow, alignment,
  marginL, marginR, marginV
) {
  return `Style: ${[
    name, fontname, fontsize,
    primaryColor, secondaryColor, outlineColor, backColor,
    bold, italic, underline, strikeOut, scaleX, scaleY, spacing, angle,
    borderStyle, outline, shadow, alignment,
    marginL, marginR, marginV, '1'
  ].join(',')}`;
}

export function validatePlanForSubtitles(plan) {
  const errors = [];

  if (!plan || typeof plan !== 'object' || Array.isArray(plan)) {
    throw new Error('production_plan.json must contain a JSON object.');
  }

  if (!Array.isArray(plan.segments) || plan.segments.length === 0) {
    errors.push('segments must be a non-empty array.');
  }

  const segments = Array.isArray(plan.segments) ? plan.segments : [];
  let previousEndMs = null;

  segments.forEach((segment, index) => {
    const label = `Segment ${segment?.id ?? index + 1}`;

    if (!segment || typeof segment !== 'object') {
      errors.push(`${label} must be an object.`);
      return;
    }

    if (!segment.start) {
      errors.push(`${label} is missing start.`);
    }

    if (!segment.end) {
      errors.push(`${label} is missing end.`);
    }

    if (typeof segment.lyric !== 'string' || segment.lyric.trim().length === 0) {
      errors.push(`${label} is missing lyric.`);
    }

    const startMs = parseTimestampToMs(segment.start);
    const endMs = parseTimestampToMs(segment.end);

    if (startMs === null) {
      errors.push(`${label} has an invalid start timestamp.`);
    }

    if (endMs === null) {
      errors.push(`${label} has an invalid end timestamp.`);
    }

    if (startMs !== null && endMs !== null && endMs <= startMs) {
      errors.push(`${label} end time must be after start time.`);
    }

    if (previousEndMs !== null && startMs !== null && startMs < previousEndMs) {
      errors.push(`${label} overlaps the previous segment.`);
    }

    if (endMs !== null) {
      previousEndMs = endMs;
    }
  });

  if (errors.length > 0) {
    throw new Error(`Subtitle validation failed:\n- ${errors.join('\n- ')}`);
  }
}

function parseArgs(args) {
  const parsed = {};

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];

    if (arg === '--input') {
      parsed.input = args[index + 1];
      index += 1;
    } else if (arg === '--output') {
      parsed.output = args[index + 1];
      index += 1;
    } else if (arg === '--help' || arg === '-h') {
      printHelp();
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return parsed;
}

async function readProductionPlan(filePath) {
  try {
    const raw = await fs.readFile(filePath, 'utf8');
    return JSON.parse(raw.replace(/^﻿/, ''));
  } catch (error) {
    if (error.code === 'ENOENT') {
      throw new Error(`production_plan.json does not exist: ${filePath}`);
    }

    if (error instanceof SyntaxError) {
      throw new Error(`production_plan.json is not valid JSON: ${filePath}`);
    }

    throw error;
  }
}

function parseTimestampToMs(timestamp) {
  if (typeof timestamp !== 'string') {
    return null;
  }

  const match = timestamp.match(/^(\d{2}):([0-5]\d):([0-5]\d)\.(\d{3})$/);
  if (!match) {
    return null;
  }

  const [, hours, minutes, seconds, milliseconds] = match;
  return (
    Number(hours) * 60 * 60 * 1000 +
    Number(minutes) * 60 * 1000 +
    Number(seconds) * 1000 +
    Number(milliseconds)
  );
}

function toAssTimestamp(timestamp) {
  const ms = parseTimestampToMs(timestamp);
  if (ms === null) {
    throw new Error(`Invalid timestamp: ${timestamp}`);
  }

  const centiseconds = Math.floor((ms % 1000) / 10);
  const totalSeconds = Math.floor(ms / 1000);
  const seconds = totalSeconds % 60;
  const totalMinutes = Math.floor(totalSeconds / 60);
  const minutes = totalMinutes % 60;
  const hours = Math.floor(totalMinutes / 60);

  return `${hours}:${pad(minutes, 2)}:${pad(seconds, 2)}.${pad(centiseconds, 2)}`;
}

function buildKaraokeText(lyric, durationSeconds) {
  const words = lyric.trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) {
    return '';
  }

  const durationCentiseconds = Math.max(1, Math.round(Number(durationSeconds || 0) * 100));
  const base = Math.floor(durationCentiseconds / words.length);
  let remainder = durationCentiseconds - base * words.length;

  return words
    .map((word) => {
      const wordDuration = base + (remainder > 0 ? 1 : 0);
      remainder -= remainder > 0 ? 1 : 0;
      return `{\\k${Math.max(1, wordDuration)}}${escapeAssText(word)}`;
    })
    .join(' ');
}

function escapeAssText(value) {
  return String(value)
    .replace(/\\/g, '\\\\')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/\r?\n/g, '\\N')
    .trim();
}

function sanitizeStyleValue(value) {
  return String(value).replace(/,/g, ' ').replace(/\r?\n/g, ' ').trim();
}

function sanitizeColor(value, fallback) {
  return typeof value === 'string' && /^&H[0-9A-Fa-f]{8}$/.test(value) ? value : fallback;
}

function clampNumber(value, fallback, min, max) {
  const number = Number(value);
  if (!Number.isFinite(number)) {
    return fallback;
  }

  return Math.min(max, Math.max(min, Math.round(number)));
}

function pad(value, length) {
  return String(value).padStart(length, '0');
}

function printHelp() {
  console.log(`Usage: node src/subtitles/generateAssSubtitles.js --input output/production_plan.json --output output/subtitles.ass`);
}

const currentFilePath = fileURLToPath(import.meta.url);
if (process.argv[1] && path.resolve(process.argv[1]) === currentFilePath) {
  await main();
}
