# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['server.py'],
    pathex=[],
    binaries=[],
    datas=[('index.html', '.')],
    hiddenimports=[
        'pedalboard',
        'pedalboard.io',
        'librosa',
        'librosa.core',
        'librosa.core.audio',
        'librosa.feature',
        'librosa.util',
        'librosa.filters',
        'resampy',
        'soundfile',
        'scipy.signal',
        'scipy.fft._pocketfft',
        'decorator',
        'lazy_loader',
        'joblib',
        'pyloudnorm',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SunoMastering',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
